"""Update UserEvent model for TDR v1.0

Revision ID: 0f534fed1806
Revises: c2dbd6977484
Create Date: 2026-08-07 20:10:19.313242

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f534fed1806"
down_revision: Union[str, Sequence[str], None] = "c2dbd6977484"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_events", sa.Column("session_id", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "user_events", sa.Column("test_session", sa.Boolean(), nullable=False)
    )
    op.create_index(
        op.f("ix_user_events_session_id"), "user_events", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_events_session_id"), table_name="user_events")
    op.drop_column("user_events", "test_session")
    op.drop_column("user_events", "session_id")
    # ### end Alembic commands ###
