"""Add Itinerary tables

Revision ID: 2e439a606765
Revises: 0f534fed1806
Create Date: 2026-08-07 21:26:14.975295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e439a606765'
down_revision: Union[str, Sequence[str], None] = '0f534fed1806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itineraries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_itineraries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itineraries'))
    )
    op.create_index(op.f('ix_itineraries_user_id'), 'itineraries', ['user_id'], unique=False)
    op.create_table('itinerary_stops',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('itinerary_id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], name=op.f('fk_itinerary_stops_itinerary_id_itineraries')),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_itinerary_stops_place_id_places')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itinerary_stops'))
    )
    op.create_index(op.f('ix_itinerary_stops_itinerary_id'), 'itinerary_stops', ['itinerary_id'], unique=False)
    op.create_index(op.f('ix_itinerary_stops_place_id'), 'itinerary_stops', ['place_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itinerary_stops_place_id'), table_name='itinerary_stops')
    op.drop_index(op.f('ix_itinerary_stops_itinerary_id'), table_name='itinerary_stops')
    op.drop_table('itinerary_stops')
    op.drop_index(op.f('ix_itineraries_user_id'), table_name='itineraries')
    op.drop_table('itineraries')
    # ### end Alembic commands ###
