"""Add trust and provenance fields to places

Revision ID: 6dc106bf8c93
Revises: 8fb0257c2209
Create Date: 2026-08-07 19:05:07.009462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc106bf8c93'
down_revision: Union[str, Sequence[str], None] = '8fb0257c2209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('places', sa.Column('source_attribution', sa.String(length=500), nullable=True))
    op.add_column('places', sa.Column('last_verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'last_verified_at')
    op.drop_column('places', 'source_attribution')
    op.drop_column('places', 'confidence_score')
    # ### end Alembic commands ###
