"""Add Verification History for Explainability Timeline

Revision ID: c2dbd6977484
Revises: 0b5dbdc6886b
Create Date: 2026-08-07 19:16:54.319722

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2dbd6977484"
down_revision: Union[str, Sequence[str], None] = "0b5dbdc6886b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("place_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("verified_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
            name=op.f("fk_verification_logs_place_id_places"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_logs")),
    )
    op.create_index(
        op.f("ix_verification_logs_place_id"),
        "verification_logs",
        ["place_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verification_logs_place_id"), table_name="verification_logs")
    op.drop_table("verification_logs")
    # ### end Alembic commands ###
