"""Add budget estimate to places

Revision ID: c8e7272323d9
Revises: e5a472d88330
Create Date: 2026-08-07 18:57:59.265120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e7272323d9'
down_revision: Union[str, Sequence[str], None] = 'e5a472d88330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('budget_estimate', sa.String(length=100), nullable=True))
    op.drop_column('places', 'opening_hours')
    op.drop_column('places', 'entry_fee')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('entry_fee', sa.VARCHAR(length=100), nullable=True))
    op.add_column('places', sa.Column('opening_hours', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('places', 'budget_estimate')
    # ### end Alembic commands ###
