"""Initial Production Schema with Knowledge Graph

Revision ID: e5a472d88330
Revises: 
Create Date: 2026-08-07 18:52:22.540986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a472d88330'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities')),
    sa.UniqueConstraint('name', name=op.f('uq_activities_name'))
    )
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('countries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries')),
    sa.UniqueConstraint('code', name=op.f('uq_countries_code')),
    sa.UniqueConstraint('name', name=op.f('uq_countries_name'))
    )
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('TRAVELER', 'CONTRIBUTOR', 'MODERATOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.String(length=36), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_states_country_id_countries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_states'))
    )
    op.create_table('subcategories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_subcategories_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subcategories'))
    )
    op.create_table('districts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], name=op.f('fk_districts_state_id_states')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_districts'))
    )
    op.create_table('cities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('district_id', sa.String(length=36), nullable=False),
    sa.Column('is_offbeat_hub', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_cities_district_id_districts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cities'))
    )
    op.create_table('villages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_villages_city_id_cities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_villages'))
    )
    op.create_table('places',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('state_id', sa.String(length=36), nullable=False),
    sa.Column('city_id', sa.String(length=36), nullable=False),
    sa.Column('village_id', sa.String(length=36), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('subcategory_id', sa.String(length=36), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('culture', sa.Text(), nullable=True),
    sa.Column('interesting_facts', sa.Text(), nullable=True),
    sa.Column('how_to_reach', sa.Text(), nullable=True),
    sa.Column('best_time_to_visit', sa.String(length=200), nullable=False),
    sa.Column('worst_time_to_visit', sa.String(length=200), nullable=True),
    sa.Column('opening_hours', sa.String(length=100), nullable=True),
    sa.Column('entry_fee', sa.String(length=100), nullable=True),
    sa.Column('crowd_factor', sa.Integer(), nullable=False),
    sa.Column('safety_rating', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),
    sa.Column('facilities', sa.JSON(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_places_category_id_categories')),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_places_city_id_cities')),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], name=op.f('fk_places_state_id_states')),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], name=op.f('fk_places_subcategory_id_subcategories')),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], name=op.f('fk_places_village_id_villages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_places'))
    )
    op.create_index(op.f('ix_places_category_id'), 'places', ['category_id'], unique=False)
    op.create_index(op.f('ix_places_city_id'), 'places', ['city_id'], unique=False)
    op.create_index(op.f('ix_places_latitude'), 'places', ['latitude'], unique=False)
    op.create_index(op.f('ix_places_longitude'), 'places', ['longitude'], unique=False)
    op.create_index(op.f('ix_places_name'), 'places', ['name'], unique=False)
    op.create_index(op.f('ix_places_state_id'), 'places', ['state_id'], unique=False)
    op.create_index(op.f('ix_places_subcategory_id'), 'places', ['subcategory_id'], unique=False)
    op.create_index(op.f('ix_places_village_id'), 'places', ['village_id'], unique=False)
    op.create_table('node_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('rel_type', sa.Enum('NEAR', 'ALTERNATIVE', 'PART_OF', 'CONNECTED_ROUTE', 'RECOMMENDED_TOGETHER', 'SAME_EXPERIENCE', 'PHOTOGRAPHY_SPOT', name='relationshiptype'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['places.id'], name=op.f('fk_node_relationships_source_id_places')),
    sa.ForeignKeyConstraint(['target_id'], ['places.id'], name=op.f('fk_node_relationships_target_id_places')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_relationships'))
    )
    op.create_index(op.f('ix_node_relationships_source_id'), 'node_relationships', ['source_id'], unique=False)
    op.create_index(op.f('ix_node_relationships_target_id'), 'node_relationships', ['target_id'], unique=False)
    op.create_table('place_activities',
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.Column('activity_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_place_activities_activity_id_activities')),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_place_activities_place_id_places')),
    sa.PrimaryKeyConstraint('place_id', 'activity_id', name=op.f('pk_place_activities'))
    )
    op.create_table('place_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('is_hero', sa.Boolean(), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_place_images_place_id_places')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_images'))
    )
    op.create_table('place_tags',
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_place_tags_place_id_places')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_place_tags_tag_id_tags')),
    sa.PrimaryKeyConstraint('place_id', 'tag_id', name=op.f('pk_place_tags'))
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_reviews_place_id_places')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.create_table('user_favorites',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_user_favorites_place_id_places')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_favorites_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'place_id', name=op.f('pk_user_favorites'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorites')
    op.drop_table('reviews')
    op.drop_table('place_tags')
    op.drop_table('place_images')
    op.drop_table('place_activities')
    op.drop_index(op.f('ix_node_relationships_target_id'), table_name='node_relationships')
    op.drop_index(op.f('ix_node_relationships_source_id'), table_name='node_relationships')
    op.drop_table('node_relationships')
    op.drop_index(op.f('ix_places_village_id'), table_name='places')
    op.drop_index(op.f('ix_places_subcategory_id'), table_name='places')
    op.drop_index(op.f('ix_places_state_id'), table_name='places')
    op.drop_index(op.f('ix_places_name'), table_name='places')
    op.drop_index(op.f('ix_places_longitude'), table_name='places')
    op.drop_index(op.f('ix_places_latitude'), table_name='places')
    op.drop_index(op.f('ix_places_city_id'), table_name='places')
    op.drop_index(op.f('ix_places_category_id'), table_name='places')
    op.drop_table('places')
    op.drop_table('villages')
    op.drop_table('cities')
    op.drop_table('districts')
    op.drop_table('subcategories')
    op.drop_table('states')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('countries')
    op.drop_table('categories')
    op.drop_table('activities')
    # ### end Alembic commands ###
